# Generated by Django 6.1.1 on 2026-09-28 07:51

import apartments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Icon key from core/templatetags/icons.py', max_length=30)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'amenities',
                'db_table': 'amenities',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'property_types',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('area', models.CharField(db_index=True, max_length=100, verbose_name='Area / neighborhood')),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monthly rent')),
                ('bedrooms', models.PositiveSmallIntegerField(help_text='0 for a studio')),
                ('bathrooms', models.PositiveSmallIntegerField()),
                ('size_sqft', models.PositiveIntegerField(blank=True, null=True, verbose_name='Size (sq ft)')),
                ('furnishing', models.CharField(choices=[('furnished', 'Furnished'), ('semi_furnished', 'Semi-furnished'), ('unfurnished', 'Unfurnished')], default='unfurnished', max_length=20)),
                ('availability', models.CharField(choices=[('available', 'Available now'), ('coming_soon', 'Available soon'), ('rented', 'Rented')], db_index=True, default='available', max_length=20)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('extra_attributes', models.JSONField(blank=True, default=dict)),
                ('contact_name', models.CharField(max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('draft', 'Unpublished'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='apartments', to='apartments.amenity')),
                ('owner', models.ForeignKey(blank=True, help_text='Profile that owns or manages this listing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments', to=settings.AUTH_USER_MODEL)),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apartments', to='apartments.propertytype')),
            ],
            options={
                'db_table': 'apartments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', max_length=255, upload_to=apartments.models.apartment_image_path, width_field='width')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='apartments.apartment')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'apartment_images',
                'ordering': ['-is_primary', 'sort_order', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('apartment',), name='one_primary_image_per_apartment')],
            },
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['status', 'city'], name='apartments_status_c418b5_idx'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['status', 'rent'], name='apartments_status_0da9a6_idx'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['status', 'bedrooms'], name='apartments_status_9ff68d_idx'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['status', '-created_at'], name='apartments_status_25b274_idx'),
        ),
        migrations.AddConstraint(
            model_name='apartment',
            constraint=models.CheckConstraint(condition=models.Q(('rent__gt', 0)), name='apartment_rent_positive'),
        ),
        migrations.AddConstraint(
            model_name='apartment',
            constraint=models.CheckConstraint(condition=models.Q(('size_sqft__isnull', True), ('size_sqft__gt', 0), _connector='OR'), name='apartment_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='apartment',
            constraint=models.CheckConstraint(condition=models.Q(('bedrooms__lte', 50), ('bathrooms__lte', 50)), name='apartment_rooms_reasonable'),
        ),
    ]
