# Generated by Django 6.1.1 on 2026-09-28 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_listing_moderation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='advance_months',
            field=models.PositiveSmallIntegerField(default=2, help_text='Months of rent paid in advance as security.', verbose_name='Advance (months)'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='floor_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0 for ground floor', null=True, verbose_name='Floor'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Building maintenance, guard, lift, generator etc.', max_digits=10, verbose_name='Service charge / month'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='tenant_preference',
            field=models.CharField(choices=[('any', 'Anyone'), ('family', 'Family'), ('bachelor', 'Bachelor'), ('female', 'Female only')], default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='apartment',
            name='total_floors',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Total floors in building'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='availability',
            field=models.CharField(choices=[('available', 'Available now'), ('coming_soon', 'Available soon'), ('booked', 'Booked'), ('rented', 'Rented')], db_index=True, default='available', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='apartment',
            constraint=models.CheckConstraint(condition=models.Q(('service_charge__gte', 0)), name='apartment_service_charge_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='apartment',
            constraint=models.CheckConstraint(condition=models.Q(('advance_months__lte', 24)), name='apartment_advance_reasonable'),
        ),
    ]
