# Generated by Django 6.1.1 on 2026-09-28 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_bangladesh_lookups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedApartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='apartments.apartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_apartments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_apartments',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'apartment'), name='unique_saved_apartment')],
            },
        ),
    ]
