# Generated by Django 6.1.1 on 2026-09-28 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0006_savedapartment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Waiting for landlord'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('completed', 'Tenancy ended')], db_index=True, default='pending', max_length=20)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('household', models.CharField(choices=[('family', 'Family'), ('bachelor', 'Bachelor'), ('female', 'Female'), ('other', 'Other')], default='family', max_length=20, verbose_name='Household type')),
                ('occupants', models.PositiveSmallIntegerField(default=1, verbose_name='Number of people')),
                ('move_in_date', models.DateField(verbose_name='Preferred move-in date')),
                ('visit_date', models.DateField(blank=True, null=True, verbose_name='Preferred viewing date')),
                ('message', models.TextField(blank=True, max_length=2000, verbose_name='Message to landlord')),
                ('landlord_note', models.TextField(blank=True, max_length=2000)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='apartments.apartment')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='bookings_tenant__2e2875_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'accepted'))), fields=('apartment',), name='one_open_booking_per_apartment'), models.CheckConstraint(condition=models.Q(('occupants__gte', 1), ('occupants__lte', 30)), name='booking_occupants_range')],
            },
        ),
    ]
